import React, { useState } from 'react';
import type { Scenario } from '../types';
import { 
  X, 
  Copy, 
  Check, 
  Download, 
  Printer, 
  FileText
} from 'lucide-react';

interface ExportReportModalProps {
  scenario: Scenario;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  scenario,
  onClose
}) => {
  const [copied, setCopied] = useState(false);

  // Build Markdown content
  const markdownText = `# Perspective AI - Executive Decision & Perspective Synthesis Briefing

**Dilemma**: ${scenario.title}  
**Domain**: ${scenario.category} | **Urgency**: ${scenario.urgency} | **Consensus Index**: ${scenario.consensusScore}%  
**Polarization Level**: ${scenario.polarizationLevel}  
**Date of Synthesis**: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

---

## 1. Executive Summary & Core Dilemma
${scenario.dilemmaPrompt}

> **Core Synthesis**: ${scenario.summary}

---

## 2. Multi-Persona Perspectives & Evaluative Stances
${scenario.personas.map(p => `### ${p.name} (${p.title})
- **Archetype**: ${p.archetype.toUpperCase()}
- **Stance**: ${p.stanceLabel} (Confidence: ${p.confidenceScore}%)
- **Axiom**: "${p.quote}"
- **Key Arguments**:
${p.keyArguments.map(arg => `  - ${arg}`).join('\n')}
- **Identified Vulnerabilities**: ${p.vulnerabilities.join('; ')}
- **Critical Trade-Off**: ${p.criticalTradeOff}
- **Proposed Safeguard**: ${p.proposedSafeguard}
`).join('\n')}

---

## 3. Consensus Insights & Strategic Tension Points
${scenario.consensusInsights.map(ci => `### ${ci.category === 'unanimous_ground' ? '🤝 [Unanimous Ground]' : ci.category === 'strategic_rift' ? '⚡ [Strategic Friction]' : '🔍 [Cognitive Bias]'} ${ci.title}
- **Impact Level**: ${ci.impactLevel}
- **Analysis**: ${ci.description}
- **Perspective Action Strategy**: ${ci.actionRecommendation}
`).join('\n')}

---

## 4. Synthesized Strategic Recommendation
${scenario.recommendations.map(r => `### ${r.pathName} (${r.archetypeRecommendation})
- **Risk Profile**: ${r.riskFactor}
- **Expected Upside**: ${r.expectedUpside}
- **Prerequisite Condition**: ${r.primaryCondition}
- **Strategic Action Plan**:
${r.actionChecklist.map(c => `  - [ ] ${c}`).join('\n')}
`).join('\n')}

---

## 5. Phased Execution Roadmap & Risk Gates
${scenario.roadmap.map(rm => `### ${rm.phase}: ${rm.title} (${rm.timeframe})
- **Key Deliverables**:
${rm.milestones.map(m => `  - ${m}`).join('\n')}
- **Risk Mitigation Trigger**: ${rm.riskMitigation}
`).join('\n')}

---
*Generated by Perspective AI — Multi-Perspective Decision & Debate Intelligence Platform*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([markdownText], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Perspective-AI-Briefing-${scenario.id}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="export-modal glass-panel" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="modal-header-left">
            <FileText size={22} className="text-cyan" />
            <div>
              <h2>Executive Perspective Synthesis Briefing</h2>
              <p className="modal-sub">Formatted multi-perspective intelligence report ready for executive sharing</p>
            </div>
          </div>
          <button type="button" className="btn-close-modal" onClick={onClose}>
            <X size={20} />
          </button>
        </div>

        <div className="modal-body-scroll export-body">
          <div className="export-toolbar glass-panel">
            <div className="toolbar-info">
              <span className="badge badge-indigo">{scenario.category}</span>
              <span className="toolbar-score">Consensus Score: {scenario.consensusScore}%</span>
            </div>

            <div className="toolbar-btns">
              <button type="button" className="btn btn-secondary btn-sm" onClick={handleCopy}>
                {copied ? <Check size={14} className="text-emerald" /> : <Copy size={14} />}
                <span>{copied ? 'Copied to Clipboard!' : 'Copy Markdown'}</span>
              </button>

              <button type="button" className="btn btn-secondary btn-sm" onClick={handleDownload}>
                <Download size={14} />
                <span>Download .md</span>
              </button>

              <button type="button" className="btn btn-primary btn-sm" onClick={handlePrint}>
                <Printer size={14} />
                <span>Print / Save PDF</span>
              </button>
            </div>
          </div>

          <div className="markdown-preview-card glass-panel">
            <pre className="markdown-preview-text">{markdownText}</pre>
          </div>
        </div>

        <div className="modal-footer">
          <button type="button" className="btn btn-secondary" onClick={onClose}>
            Close
          </button>
          <button type="button" className="btn btn-primary" onClick={handleDownload}>
            <Download size={16} />
            <span>Download Executive Briefing</span>
          </button>
        </div>
      </div>
    </div>
  );
};
